services:
  apache2:
    build:
      context: .
      dockerfile: apache2
    container_name: apache2
    ports:
      - "80:80"
    volumes:
      - ./squirrel:/var/www/mail
    privileged: true
    networks:
      - net

  mail:
    build:
      context: .
      dockerfile: mail
    container_name: mail
    privileged: true
    networks:
      - net

networks:
  net:
    driver: bridge