services:
  mail:
    image: mail
    container_name: mail
    privileged: true

  # ubuntu:
  #   image: ubuntu:latest
  #   container_name: ubuntu
  #   networks:
  #     - local-net
  #   privileged: true
  #   tty: true