services:
  apache2:
    build:
      context: .
      dockerfile: apache2
    container_name: apache2
    ports:
      - "80:80"
    volumes:
      - ./squirrel:/var/www/mail
    privileged: true
    networks:
      - net

  dovecot:
    build:
      context: .
      dockerfile: dovecot
    container_name: dovecot
    privileged: true
    networks:
      - net
      
  postfix:
    build:
      context: .
      dockerfile: postfix
    container_name: postfix
    privileged: true
    networks:
      - net

networks:
  net:
    driver: bridge