services:
  mail:
    image: mail
    container_name: mail
    networks:
      - local-net
    privileged: true
    tty: true

  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    networks:
      - local-net
    privileged: true
    tty: true

networks:
  local-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.1.0/24